spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshop
    username: petshop
    password: Petshop1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update